---
- name: Setup workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Setup SSH environment
      ansible.builtin.import_tasks: tasks/prep-ssh.yaml

    - name: Brew Cask App installation (failure expected)
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: latest
      with_items:
        - visual-studio-code
        - qlmarkdown
        - drawio
        - notion
        - obs
      tags: [ apps ]
    - name: More brew apps
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible-lint
        - podman
        - jq
        - gojq
        - go
        - openshift-cli
        - kubernetes-cli
        - kubectl
        - minio-mc
        - govc
      tags: [ apps ]

# MAC DS_Store supress
    - name: Disable DS_Store on USB Drives
      community.general.osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteUSBStores
        type: bool
        value: true
        state: present
      tags: [ config ]
    - name: Disable DS_Store on Network Drives
      community.general.osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true
        state: present
      tags: [ config ]

# Git Configuration section
    - name: User git ignore DS_Store
      ansible.builtin.lineinfile:
        path: ~/.config/git/ignore
        line: '.DS_Store'
        create: true
        mode: '0644'
      tags: [ config ]
    - name: User git ignore Icon
      ansible.builtin.lineinfile:
        path: ~/.config/git/ignore
        line: 'Icon^M'
        create: true
        mode: '0644'
      tags: [ config ]
    - name: Git config Global User
      community.general.git_config:
        name: user.name
        value: "Jeff Kelly"
        scope: global
      tags: [ config ]
    - name: Git config global email
      community.general.git_config:
        name: user.email
        value: jeff.kelly@mobia.io
        scope: global
      tags: [ config ]
