---
- name: Setup workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Setup SSH environment
      ansible.builtin.import_tasks: tasks/prep-ssh.yaml

    - name: Brew Cask App installation (failure expected)
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: latest
      with_items:
        - visual-studio-code
        - qlmarkdown
        - drawio
        - notion
        - obs
    - name: More brew apps
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible-lint
        - podman
        - jq
        - gojq
        - go
        - openshift-cli
        - kubernetes-cli
        - kubectl
        - minio-mc
        - govc
