---
# Key lookup prep for setting up ssh keys from secure vault - WIP
- name: Check existing key
  ansible.builtin.stat:
    path: ~/.ssh/{{ defaultkeyname }}
  register: deployedKey

- name: DEBUG key name
  ansible.builtin.debug:
    msg: "The key to look for is {{ defaultkeyname }}"

- name: DEBUG key status
  ansible.builtin.debug:
    msg: "The {{ defaultkeyname }} file or directory exists"
  when: deployedKey.stat.exists
